#!/usr/bin/env lua
package.path = package.path .. ";../../?.lua"

LibStub = setmetatable({}, {
    __call = function(_, name, noError)
        return {
            GetAddon = function(addonName)
                return {}
            end,
        }
    end,
})

local version = (arg[1] or ''):match("^%s*(.-)%s*$")
local changelog = require("UI.Changelog")

if not version then
    print("Usage: print-changelog <version>")
    os.exit(1)
end

if not changelog[version] then
    print("Error! No changelog found for version `" .. version .. "`")
    os.exit(1)
end

log = changelog[version]

for _, entry in ipairs(log) do
    print("- " .. entry)
end
