---@type DungeonDocs
local DD = LibStub("AceAddon-3.0"):GetAddon("DungeonDocs")

---@type PlayerNote[]
local notes = {
	{
		-- bossName = "Blightbone",
		ddid = "tnw1",
		primaryNote = "(1) Aim belch away from group if targeted\n(2) Kill adds ASAP (stun and CC if needed)",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- bossName = "Amarth, The Harvester",
		ddid = "tnw2",
		primaryNote = "(1) Always interrupt the boss\n(2) Kill the adds ASAP starting with the mage\n(3) Avoid beam of death & decay",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- bossName = "Surgeon Stitchflesh",
		ddid = "tnw3",
		primaryNote = "(1) Aim the meat hook (arrow) at the boss to pull him down\n(2) Save CDs for when boss is pulled down\n(3) Hit boss with meat hook arrow even after pulled down",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- bossName = "Nalthor the Rimebinder",
		ddid = "tnw4",
		primaryNote = "(1) Avoid swirlies\n(2) Ranged players spread out\n(3) When someone gets frozen, move out of their circle ASAP. Do NOT dispel the frozen buff until circle is empty\n(4) Avoid crossing each other's paths during the comet storm\n(5) If sent away, go through gauntlet & kill the mob at the end",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Patchwerk Soldier",
		ddid = "tnw5",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Blight Bag",
		ddid = "tnw6",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Corpse Harvester",
		ddid = "tnw7",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Stitched Vanguard",
		ddid = "tnw8",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Zolramus Gatekeeper",
		ddid = "tnw9",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Flesh Crafter",
		ddid = "tnw10",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Zolramus Sorcerer",
		ddid = "tnw11",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Zolramus Bonecarver",
		ddid = "tnw12",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Zolramus Necromancer",
		ddid = "tnw13",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Brittlebone Mage",
		ddid = "tnw14",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Brittlebone Warrior",
		ddid = "tnw15",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Skeletal Marauder",
		ddid = "tnw16",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Zolramus Bonemender",
		ddid = "tnw17",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Nar'zudah",
		ddid = "tnw18",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Skeletal Monstrosity",
		ddid = "tnw19",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Brittlebone Crossbowman",
		ddid = "tnw20",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Shuffling Corpse",
		ddid = "tnw21",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Corpse Collector",
		ddid = "tnw22",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Kyrian Stitchwerk",
		ddid = "tnw23",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Spare Parts",
		ddid = "tnw24",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Loyal Creation",
		ddid = "tnw25",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Separation Assistant",
		ddid = "tnw26",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Stitching Assistant",
		ddid = "tnw27",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Goregrind",
		ddid = "tnw28",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Goregrind Bits",
		ddid = "tnw29",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Rotspew Leftovers",
		ddid = "tnw30",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Rotspew",
		ddid = "tnw31",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
	{
		-- name = "Stitchflesh's Creation",
		ddid = "tnw32",
		primaryNote = "",
		healerNote = "",
		damageNote = "",
		tankNote = "",
	},
}

--- @type ProfileDungeonNotes
local profileDungeonNotes = {
	dungeonName = "The Necrotic Wake",
	notes = notes,
}

DD.profiles.DefaultFallback_InitDocs(profileDungeonNotes)
