local DD = LibStub("AceAddon-3.0"):GetAddon("DungeonDocs")


local notes = {
  {
    -- bossName = "Chopper Redhook",
    ddid = "sob1",
    primaryNote = "(1) Kite boss into bombs (save big DPS CDs until boss is stunned, he takes more damage)\n(2) Avoid bombs\n(3) Run away when he sucks you in\n(4) Avoid swirlies\n(5) Cleave adds",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- bossName = "Dread Captain Lockwood",
    ddid = "sob2",
    primaryNote = "(1) Avoid stuff on ground\n(2) Kill adds in intermission phase",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- bossName = "Hadal Darkfathom",
    ddid = "sob3",
    primaryNote = "(1) Avoid swirlies\n(2) When [TIDAL SURGE] is cast, stand on the opposite side of the statue\n(3) Follow Tank",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- bossName = "Viqgoth",
    ddid = "sob4",
    primaryNote = "(1) Kill Demolishing Terror before Gripping Terror\n(2) Avoid Swirlies\n(3) When tenticles are killed on a platform, hop into cannon and shoot boss\n(4) Repeat on second platform\n(5) Repeat on boat platform",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Scrimshaw Gutter",
    ddid = "sob5",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Blacktar Bomber",
    ddid = "sob6",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Scrimshaw Enforcer",
    ddid = "sob7",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Waveshaper",
    ddid = "sob8",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Raider",
    ddid = "sob9",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Riptide Shredder",
    ddid = "sob10",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Snarling Dockhound",
    ddid = "sob11",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Curseblade",
    ddid = "sob12",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Powdershot",
    ddid = "sob13",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Commander",
    ddid = "sob14",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Spotter",
    ddid = "sob15",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Deckhand",
    ddid = "sob16",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Cannoneer",
    ddid = "sob17",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Bilge Rat Pillager",
    ddid = "sob18",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Bilge Rat Buccaneer",
    ddid = "sob19",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Bilge Rat Demolisher",
    ddid = "sob20",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Bilge Rat Tempest",
    ddid = "sob21",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Bilge Rat Cutthroat",
    ddid = "sob22",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Invader",
    ddid = "sob23",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Destroyer",
    ddid = "sob24",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Waveshaper",
    ddid = "sob25",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Powdershot",
    ddid = "sob26",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Ashvane Sniper",
    ddid = "sob27",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Curseblade",
    ddid = "sob28",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Irontide Powdershot",
    ddid = "sob29",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
  {
    -- name = "Scrimshaw Gutter",
    ddid = "sob30",
    primaryNote = "",
    healerNote = "",
    damageNote = "",
    tankNote = "",
  },
}

local dungeonData = {
  name = "Siege of Boralus",
  notes = notes,
}


DD:ProfilesDefault_InitDocs(dungeonData)
