name: CD

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets entire git history, needed for automatic changelogs

      - name: Package and release
        uses: BigWigsMods/packager@v2
