name: CD

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets entire git history, needed for automatic changelogs

      - name: Extract version from .toc file
        id: toc_version
        run: |
          # Extract the version from the .toc file
          toc_version=$(grep -oP '## Version:\s*\K.*' DungeonDocs.toc | tr -d '\r')
          echo "Extracted addon version: $toc_version"
          echo "toc_version=$toc_version" >> $GITHUB_ENV
        
      - name: Compare with tag version
        run: |
          tag_version="${GITHUB_REF#refs/tags/}"

          echo "Tag version: $tag_version"
          echo "Addon version: $toc_version"

          # Compare versions
          if [ "$toc_version" != "$tag_version" ]; then
            echo "Error: Addon version ($toc_version) does not match tag version ($tag_version)"
            exit 1
          else
            echo "Versions match!"
          fi
        env:
          toc_version: ${{ env.toc_version }}

      - name: Package and release
        uses: BigWigsMods/packager@v2
